### PR TITLE
Use superstruct for queue data

### PR DESCRIPTION
**Pull request by ludeeus**

### CODE REVIEW

**Comment by bramkragten** [comment]
Aren't we always in control of this data? It is asserted before? What is the benefit of doing this?

**Comment by ludeeus** [comment]
The benefit is the defaulted, when/if we change the data while a queue has started

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
If we change the data, wouldn't it be better if we throw out the queue data, as the counts need to restart?

It's going to be less fragile if we throw bad data out and start over instead of trying to patch it up.

**Comment by ludeeus** [comment]
I think we should do both, i can implement schema versions in the upcoming schedule handler

**Comment by balloob** [comment]
How can we both try to patch old formats to new formats and reject old formats at the same time? 😄

**Pull request closed without merging**
