### PR TITLE
Add Cloudflared Add-On

### PR DESCRIPTION
**Pull request by brenner-tobias**
Add the widely used [Add-On Cloudflared](https://github.com/brenner-tobias/addon-cloudflared).

The Add-on can be found in the [analytics JSON for add-ons](https://analytics.home-assistant.io/addons.json) (9074a9fa_cloudflared).

### CODE REVIEW

**Comment by ludeeus** [comment]
We will only show add-ons that are default in the Supervisor (This is the same we do for integrations; we only show core and not custom).

The raw data can still be accessed in the raw form as you linked.

Thanks anyway 👍

**Comment by brenner-tobias** [comment]
Thanks a lot for your feedback. Can you elaborate on the reasoning behind this? 

The page does suggest to show a list of all add-ons ranked by usage, so I do not get the need to limit it, if there are enough users of an add-on. From my perspective, the whole idea of an open source community is to also promote 3rd party additions which are not necessarily created by the core team, so I do not get this restriction.

I did apply to add the add-on to the hassio-community add-ons, which was also declined, so I there are not really any possibilities for this to be more prominent, which is very unfortunate for the community from my perspective.

**Comment by ludeeus** [comment]
> Thanks a lot for your feedback. Can you elaborate on the reasoning behind this?

There is not really anything more to elaborate on.
The website only shows default integrations and add-ons.

Authors of custom integration and add-ons can still use and show the values as they wish.

**Comment by brenner-tobias** [comment]
Thanks again, but I do believe there is, for example why you choose to exclude valid and widely used Add-Ons from this page and block such a PR. I am not asking anyone to actively update this list, but at least to consider the relevance of 3rd party add-ons once they are raised.

What is the benefit of this analytics page if not to show all relevant add-ons and their number of installations, at no point is this hinting that it shows "Default Add-ons" only. I do believe that our add-on has reached a relevant number or installations and users, so I think questioning your reasoning is very much valid.

All I am asking is pretty simple: I don't see a single reason not to add our add-on here so why do you chose not to?

**Pull request closed without merging**
